### ISSUE TITLE
socket: too many open files

### ISSUE THREAD

**Issue by FischC** [uniqush/uniqush-push#104]
Hi!

I'm currently running into serious issues when running uniqush push server on CentOS Linux 6.0! Even if set the file limit to 8192 in limits.conf I do receive "socket: too many open files" when sending push messages @ approx 60 pushes/sec.:

[Push][Error] 2016/03/07 14:22:31 RequestID=XXX Service=XXX Subscriber=XXX PushServiceProvider=XXX DeliveryPoint=gcm:XXX Failed: Post https://android.googleapis.com/gcm/send: dial tcp: lookup android.googleapis.com on 193.33.114.2:53: dial udp 193.33.114.2:53: socket: too many open files

~ cat /etc/security/limits.conf
[snip]
*               soft    nofile            8192
*               hard    nofile            8192

~ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 30456
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 8192
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

A possible workaround could be throttling the throughput on the "WebFrontend" but this is only a temporary solution as I need to keep up with approx 60-100 pushes/second.

Any suggestion?

Thanks & kind regards
// Clemens

**Comment by TysonAndre** [comment]
Port 53 is used for DNS. https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
Without any extra information, I'd assume the problem is due to too many DNS lookups being performed at the same time.

Caching dns queries is something that should be done at the OS level. 

1. Try installing dnsmasq (Probably available via `yum install dnsmasq`) - https://lukas.zapletalovi.com/2012/09/ultra-simple-dhcp-and-caching-dns-on-rhel6.html may or may not help. I haven't set up dnsmasq recently.
   (Note: If dnsmasq is misconfigured, dns lookups will fail, causing outgoing connections to stop working)
2. Try running uniqush-push on a different OS. I'm not familiar with DNS on centos 6.0
3. Fork uniqush-push to use an in-program DNS caching module such as https://godoc.org/github.com/abursavich/nett (Haven't looked at the code of that). Change the places which call http.NewRequest
4. Hardcoding IPs won't work, they change frequently. https://groups.google.com/forum/#!topic/android-gcm/Cz4vp5n3mMo

I'd try 2 and 3 first.

**Comment by mishan** [comment]
:+1: To @TysonAndre 's analysis. Your OS should really be caching these DNS requests. CentOS 6.0 is really antiquated but I'm surprised it would exhibit such behavior. We run `nscd` on our CentOS 6.5 servers that run our uniqush-push tier.

**Comment by TysonAndre** [comment]
There's one other possibility: Something else was opening up too many connections, causing dns lookups to fail to open a file. There have been several bugs found and fixed recently relating to closing connections. I'd recommend upgrading to uniqush 2.1, when it's released (hopefully this week)

Does anything stand out in `sudo lsof` (Is the most common node `TCP`, `UDP`, or something else).

How many lines are in `sudo netstat` (This logs active connections), and what's the most common foreign address and state from the output of netstat?

**Comment by FischC** [comment]
Good morning!

Thanks for the feedback and your advice. I did some additional analysis and the DNS issue seems to be only the tip of the iceberg and I suspect the connection pool to have caused the problem. But I'll stop here, update to 2.1! Thanks for your support and I'll close this issue for now ...

Cheers
// Clemens
