### ISSUE TITLE
Any available test for android to exercise uniqush-push?

### ISSUE THREAD

**Issue by kartlee** [uniqush/uniqush-push#131]
Hi Folks,

Do you have any readymade test for android client which I can use and play with uniqush push?

-Karthik

**Comment by TysonAndre** [comment]
If you're talking about sample android apps and sample app servers communicating with uniqush-push, then there's no in depth tutorials, to my knowledge. Looking for blog posts didn't find anything either.

Do you mean something along the lines of (The link is for iOS&APNS, not Android&GCM, and I haven't looked at it in much detail) http://tleyden.github.io/blog/2016/02/03/setting-up-uniqush-with-apns/ , but for GCM?

I'd recommend looking at https://developers.google.com/cloud-messaging/android/start for an example Android app that can receive push notifications.

Also, 

1. Setting up redis and configuring is described in http://uniqush.org/documentation/install.html and linked pages. The blog post for APNS set up redis another way.
2. Writing an app server: Could use curl just to test things out, similar to what was mentioned in the APNS blog post. But add `projectid` and `apikey` instead of `cert` and `key`, `pushservicetype=gcm` instead of `pushservicetype=apns`, `regid` instead of `devtoken`, etc. See http://uniqush.org/documentation/usage.html
3. The Android App : See https://developers.google.com/cloud-messaging/android/start

**Comment by kartlee** [comment]
Thanks for your reply. I will give a shot as you recommended.
