### ISSUE TITLE
Create official release with FCM support?

### ISSUE THREAD

**Issue by kartlee** [uniqush/uniqush-push#134]
Hi,

Do we have plans to migrate to fcm? If so, whats the eta for it?

-Karthik

**Comment by mishan** [comment]
It's not something we have planned currently -- what are you trying to get from it? It seems the biggest difference is it supports XMPP, allowing bidirectional communication.

**Comment by TysonAndre** [comment]
XMPP and a built in analytics suite https://firebase.google.com/docs/cloud-messaging/#key_capabilities

The APIs we'd use for FCM and GCM seem to be the same (Just one API: sending pushes to a device and processing the response)

I think APNS HTTP/2 and web GCM would probably be implemented by the maintainers before this.

As for things you one gets out of this... *I think device groups were also part of gcm, never mind*

-  Firebase had a concept of "device groups" similar to Uniqush "subscribers" (You could associate user ids to a list of push notifications. https://firebase.google.com/docs/cloud-messaging/send-message#send_messages_to_device_groups
- So I assume it would automatically track when a device token becomes invalid and remove it from the DB(We only know about this when a push is attempted)
- Uniqush would probably have higher latency and use more external network traffic for fetching subscribers if we used Firebase's subscription mechanism instead of redis (assuming redis is in the same data center). Haven't checked.
- https://firebase.google.com/docs/cloud-messaging/android/device-group it's limited to 20, which seems reasonable. What it does when there's more than that isn't really documented
- It doesn't seem to have a way to list all of the devices in a device group

There's other interesting features, but this would also require writing migration documentation/scripts to migrate

**Comment by TysonAndre** [comment]
https://github.com/uniqush/uniqush-push/pull/139 is related

**Comment by TysonAndre** [comment]
Probably worth doing this for new apps (With the exact same API as GCM currently has).
I'd need to set up an FCM test/example app to verify that the current API for registering and pushing still works for pushing from uniqush-push

**Comment by muspelheim** [comment]
@TysonAndre Hello, what about this issue?

**Comment by TysonAndre** [comment]
#148 was merged today. It adds support for FCM. I finished verifying the FCM test/example app with the emulator.

If you have uniqush version 2.2.1 or greater (on master branch), it supports `pushservicetype=fcm`
- Will create release tag after more thorough testing of GCM (it was refactored to share code with FCM. Unit tests pass)

Setup, subscribing, and pushing is currently the same as GCM. https://github.com/uniqush/uniqush-push/pull/148#issuecomment-308930427

- At the time of writing, uniqush has identical features for GCM and FCM.
  I haven't got around to checking if potential new features mentioned in https://github.com/uniqush/uniqush-push/issues/134#issuecomment-243328626 would have good use cases as part of uniqush and are feasible to implement.
