### ISSUE TITLE
Does Uniqush support VOIP Push from Apple

### ISSUE THREAD

**Issue by smolskyaleksey** [uniqush/uniqush-push#202]
There are many advantages to using PushKit to receive VoIP pushes:
* VoIP pushes are considered high-priority notifications and are delivered without delay.
* **VoIP pushes can include more data than what is provided with standard push notifications.** 

You construct this payload as a JSON dictionary and send it as the body content of your HTTP/2 message. The maximum size of the payload depends on the notification you are sending:

* For regular remote notifications, the maximum size is 4KB (4096 bytes)
* **For Voice over Internet Protocol (VoIP) notifications, the maximum size is 5KB (5120 bytes)
NOTE**

If you are using the legacy APNs binary interface to send notifications instead of an HTTP/2 request, the maximum payload size is 2KB (2048 bytes)

I found in code like
``` php
maxPayLoadSize int = 2048

if err == nil && len(req.Payload) > requestProcessor.GetMaxPayloadSize() {
	err = push.NewBadNotificationWithDetails(fmt.Sprintf("payload is too large: %d > %d", len(req.Payload), requestProcessor.GetMaxPayloadSize()))
}
```

**Comment by TysonAndre** [comment]
It might support VOIP push if you just pass it the correct certificate, and configure bundleid for /addpsp (com.myapp.voip), and set `-d uniqush.http2=1` with every single `/push`? I don't have any apps that request VOIP permissions to test that with, neither do other maintainers (I also don't have a macbook for Xcode to test in sandbox).

- If this does work, knowing that would be useful.

It doesn't seem like there's a distinction between the payloads that are sent for VOIP and for regular push payloads. (Though VoIP is treated like content-available (hidden?))

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW5

Uniqush added HTTP/2 support a while ago, this can be enabled via passing `-d uniqush.http2=1` to the request to **`/push`**. (Not yet an option for /addpsp).

- If you use HTTP2 with a *regular* certificate, you have to set `bundleid=com.myapp` for that app id when calling `/addpsp` (for whatever your app's bundle id is)
   (Because of things like test builds, that bundle id may be different in different development builds. I'm planning to add an option to override that when subscribing (Alongside device token))
- If you use HTTP2 with a *VoIP* certificate, I gather that you'd want to set `-d bundleid=com.myapp.voip` instead of `com.myapp`. But I haven't tested that yet. (That may be a use case for passing bundleid with push? Also see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW5)

**Comment by smolskyaleksey** [comment]
Yes, but code that I show us check payload size and throw error. Apple's Voip push can be more them 2kb. Does it check pass or throw error "payload is too large: %d > %d"? I dont see any distinction of size between regular and voip payload.

**Comment by TysonAndre** [comment]
This should be possible in 2.5.0 passing uniqush.apns_voip=1 to the /push call, if the certificate is a VoIP certificate

**Comment by smolskyaleksey** [comment]
Thx a lot.
