### ISSUE TITLE
Unable to Download Uniqush tar File

### ISSUE THREAD

**Issue by ibr123** [uniqush/uniqush-push#213]
Hi,

im trying to download the tar file for Uniqush from the following [page](http://uniqush.org/downloads.html) yet i keep getting bad request page (502)

![error uni](https://user-images.githubusercontent.com/26926171/39743171-c32c66ce-52a8-11e8-8f01-4404c49aedb8.png)

is there any alternative link? or is there fixing for this issue soon?

Thanks

**Comment by monnand** [comment]
You can download the tar file from github as well:
https://github.com/uniqush/uniqush-push/releases

Not sure what happened to the server though.

**Comment by TysonAndre** [comment]
@monnand it looks like the admin host is no longer accessible via the method I used to upload the 2.5.0 binaries a while back. The home page or site as a whole is also inaccessible, according to cloudflare

I still have a local checkout of most of the old rpms, and can reupload those. Miscellaneous files that weren't part of uniqush-www such as index.zh.html aren't included.

**Comment by monnand** [comment]
Not sure what happened though. I probably should transfer the domain to you
so that you can point it to somewhere else. I will take a look this weekend.

**Comment by TysonAndre** [comment]
@monnand  - https://help.github.com/articles/using-a-custom-domain-with-github-pages/ might free us from the need to maintain our own servers.

I already experimented with github pages and set up https://uniqush.github.io/uniqush-www/

- The only remaining task would be to change the uniqush download links to link to the github release tags for the corresponding tags (And maybe have me upload any missing rpms/debs to the corresponding github releases)

  (Possibly avoiding direct linking to github deb files and link to the release page instead)

  E.g. https://uniqush.github.io/uniqush-www/downloads.html is currently dead links (Github discourages using git branches for distribution of large binary blobs)

**Comment by monnand** [comment]
OK... Now I know the reason. I had 2 VPS, one for uniqush.org and one for my personal blog. Because I was too lazy to write any blog, so I decided to stop the sever which hosts my blog. And.. of course, I stopped the wrong server.

The good news is: every release after 1.4.0 are [available](https://github.com/uniqush/uniqush-push/releases). There's not too much stuff to recover. I will take a look at the setup of github pages, at least, the domain name part.

Thank you, @TysonAndre for taking care of uniqush!

**Comment by monnand** [comment]
[uniqush.org](http://uniqush.org) is now pointing to the github page. The download page should be easy to change. There is also the blog subdomain. I will take a look at them next week.

**Comment by monnand** [comment]
@TysonAndre , It turned out to be my host provider changed the IP address of the server. I just sent you an email about the details. You should be able to log into the sever with your keys using the new address. In the mean time, I'll change my DNS settings back tomorrow. (In fact, at this point, I don't even know if I should just keep the settings and use github pages from now on, or should I use the old server.)

**Comment by ibr123** [comment]
@TysonAndre the AWS is paid services, but its good and reliable, i have used it before.
to minimize the cost using AWS, i suggest to get a Reserved Instance (ec2 instance) for hosting the website, its costs much less than On Demand (ec2 instance), but it can't be stopped anytime, and for storage services you can use Glacier for archiving the Binaries, its very cheap, but slow, and when you in need of using the binaries inside the Glacier, you can migrate them from the Glacier to an S3 (i think it takes 3 hours or so).
and for migration code you can use
1- Spot (ec2 instances) its a very cheap ec2 instances based on bidding, so if someone out bid you, you can will lose the instance, but can bid for another one
2- On Demand (ec2 instance) but its more expensive but no one can out bid you and you can close it after you finish
NOTE: Azure is also a good choice as well
