### ISSUE TITLE
maxPayLoadSize in apns.go

### ISSUE THREAD

**Issue by FischC** [uniqush/uniqush-push#76]
Hi!

Currently the maxPayLoadSize is set to 256 bytes (in "srv/apns.go" @line#43). Introducing iOS8 the payload size was increased to 2k (https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW1).
Is there any plan to adjust this value and/or make it configurable?

Thanks
// Clemens

**Comment by martinhpedersen** [comment]
+1

It would be very nice to be able to push payloads > 256 through uniqush-push, now that it is supported by apns.

**Comment by mishan** [comment]
I could see making it configurable. My concern is for the use case of where a subscriber could have pre-iOS 8 devices and post-iOS8 devices registered. If there's a way to tell from device ID or something, that'd be great, otherwise maybe we'd want to consider storing some flag in Redis.

The problem I can think of then -- you start sending 2k payloads over and uniqush-push can't deliver to some of the devices because they're too long.

But maybe just adding a configuration is good enough for now -- users of uniqush-push could decide what's appropriate for them. Eventually I imagine there won't be too many Apple devices with < iOS8.

**Comment by martinhpedersen** [comment]
Hi mishan,

I have found similar issues in related projects. Have a look at https://github.com/jleclanche/django-push-notifications/issues/79 and https://github.com/groupme/em-apn/pull/16.

It seems like the conclusion is that the new limit is backwards compatible and will work for post-iOS8 devices also.

**Comment by mishan** [comment]
Thanks! I've merged changes to apns.go to bump the limit to the 2kB one now. We are using this in production at if(we)
